### ISSUE TITLE
Support SvelteKit 2

### ISSUE THREAD

**Issue by dgrebb** [accuser/svelte-plausible-analytics#12]
SvelteKit 2 is out. It would be swell if support was added for `peerDependencies` :)

**Comment by till** [comment]
Can either of you publish a git-tag and a npm release?

**Comment by till** [comment]
@dgrebb I tried installing from the git-repo directly, but it fails with:

```
[plugin:vite:import-analysis] Failed to resolve entry for package "@accuser/svelte-plausible-analytics". The package may have incorrect main/module/exports specified in its package.json.
```

```diff
--- a/rootfs/app/package.json
+++ b/rootfs/app/package.json
@@ -16,7 +16,7 @@
     "test": "playwright test"
   },
   "devDependencies": {
-    "@accuser/svelte-plausible-analytics": "^0.2.0",
+    "@accuser/svelte-plausible-analytics": "https://github.com/accuser/svelte-plausible-analytics.git#6e2b8381b489aacc925840b43b141d89f36f03d0",
     "@dinero.js/currencies": "2.0.0-alpha.13",
     "@ory/client": "^1.1.21",
     "@playwright/test": "^1.31.2",
lines 4-46/46 (END)
```

Is there a better way to do this?

**Comment by dgrebb** [comment]
@till you want this format: `"svelte-plausible-analytics": "accuser/svelte-plausible-analytics#6e2b8381b489aacc925840b43b141d89f36f03d0"`

or `npm i -D accuser/svelte-plausible-analytics#6e2b8381b489aacc925840b43b141d89f36f03d0`

However, neither of these will work because the `dist` directory isn't tracked. So there are a few options:

1. pull the repo, run `npm run build`, then use `npm install -D ../path/to/svelte-plausible-analytics`
2. pull the repo, remove `dist` from `.gitignore`, `npm run build`, and push your own branch, which would allow you to `npm i -D till/svelte-plausible-analytics#hash` or `npm i -D till/svelte-plausible-analytics#branch-name`
3. use this downstream fork temporarily, which has the `dist` directory tracked: `npm i -D dgrebb/svelte-plausible-analytics#v1.0.0`

If going the local directory route, you'll end up with this in `package.json`:

`"svelte-plausible-analytics": "file:../svelte-plausible-analytics",`

**Comment by till** [comment]
@dgrebb thanks for helping. When I use your fork, I get a similar error:

```
[plugin:vite-plugin-svelte] Error while preprocessing /Users/till/Documents/workspaces/app/node_modules/@accuser/svelte-plausible-analytics/dist/PlausibleAnalytics.svelte - src attribute must be string

/Users/till/Documents/workspaces/app/node_modules/@accuser/svelte-plausible-analytics/dist/PlausibleAnalytics.svelte
```

```diff
diff --git a/rootfs/app/package.json b/rootfs/app/package.json
index b3e555a..cf6ec00 100644
--- a/rootfs/app/package.json
+++ b/rootfs/app/package.json
@@ -16,7 +16,7 @@
     "test": "playwright test"
   },
   "devDependencies": {
-    "@accuser/svelte-plausible-analytics": "^0.2.0",
+    "@accuser/svelte-plausible-analytics": "github:dgrebb/svelte-plausible-analytics#v1.0.0",
     "@dinero.js/currencies": "2.0.0-alpha.13",
     "@ory/client": "^1.1.21",
     "@playwright/test": "^1.31.2",
```

**Comment by dgrebb** [comment]
@till I'll take a look at this in bit. Are you using TypeScript?

**Comment by till** [comment]
@dgrebb no, using JavaScript. Thank you for looking. I'd guess that the tag does not include all the changes from yesterday?

**Comment by dgrebb** [comment]
@till not sure. I'm also using vanilla JS and do not get that error. Here's another branch to try: `npm i -D dgrebb/svelte-plausible-analytics#downstream/release-1.0.0-alpha`, 

This is an exact copy of `main`, but includes `dist`.

Can you please share the `<PlausibleAnalytics />` component implementation from your project?

**Comment by till** [comment]
I just tried again with your `release-1.0.0-alpha` branch. Same result. I deleted the library from `node_modules/@accuser/` too to ensure I am re-installing it etc.:

```sh
❯ cat node_modules/@accuser/svelte-plausible-analytics/package.json
{
	"name": "@accuser/svelte-plausible-analytics",
	"version": "1.0.0",
	"description": "Plausible Analytics library for SvelteKit apps.",
	"keywords": [
...
```

All I do in my root layout:

```js
import { PlausibleAnalytics } from '@accuser/svelte-plausible-analytics'
// other code
<PlausibleAnalytics domain={[ownDomain, 'rollup.example.org']} />
```

When I remove it, the page loads. I've only tried this with `npm run dev` (aka `vite --host --port 3000`) yet. 

Complete log:

```
{
  name: 'Error',
  id: '/Users/till/Documents/workspaces/rootfs/app/node_modules/@accuser/svelte-plausible-analytics/dist/PlausibleAnalytics.svelte',
  message: 'Error while preprocessing /Users/till/Documents/workspaces/rootfs/app/node_modules/@accuser/svelte-plausible-analytics/dist/PlausibleAnalytics.svelte - src attribute must be string',
  frame: '',
  code: undefined,
  stack: 'Error: Error while preprocessing /Users/till/Documents/workspaces/rootfs/app/node_modules/@accuser/svelte-plausible-analytics/dist/PlausibleAnalytics.svelte - src attribute must be string\n' +
    '    at getTagInfo (/Users/till/Documents/workspaces/rootfs/app/node_modules/svelte-preprocess/dist/modules/tagInfo.js:32:19)\n' +
    '    at /Users/till/Documents/workspaces/rootfs/app/node_modules/svelte-preprocess/dist/autoProcess.js:95:115\n' +
    '    at script (/Users/till/Documents/workspaces/rootfs/app/node_modules/svelte-preprocess/dist/autoProcess.js:147:39)\n' +
    '    at process_single_tag (file:///Users/till/Documents/workspaces/rootfs/app/node_modules/svelte/src/compiler/preprocess/index.js:285:27)\n' +
    '    at file:///Users/till/Documents/workspaces/rootfs/app/node_modules/svelte/src/compiler/preprocess/replace_in_code.js:30:4\n' +
    '    at String.replace (<anonymous>)\n' +
    '    at calculate_replacements (file:///Users/till/Documents/workspaces/rootfs/app/node_modules/svelte/src/compiler/preprocess/replace_in_code.js:28:9)\n' +
    '    at replace_in_code (file:///Users/till/Documents/workspaces/rootfs/app/node_modules/svelte/src/compiler/preprocess/replace_in_code.js:69:29)\n' +
    '    at process_tag (file:///Users/till/Documents/workspaces/rootfs/app/node_modules/svelte/src/compiler/preprocess/index.js:302:32)\n' +
    '    at Module.preprocess (file:///Users/till/Documents/workspaces/rootfs/app/node_modules/svelte/src/compiler/preprocess/index.js:360:31)',
  plugin: 'vite-plugin-svelte',
  pluginCode: '<script context="module">const plausible = (event, options) => window.plausible(event, options);\n' +
    '</script>\n' +
    '\n' +
    '<script>import { onMount } from "svelte";\n' +
    'import { dev } from "$app/environment";\n' +
    'import { page } from "$app/stores";\n' +
    'import { pa } from "./store.js";\n' +
    'onMount(() => {\n' +
    '  pa.subscribe((events) => {\n' +
    '    let next = events.length && events.shift();\n' +
    '    while (next) {\n' +
    '      const { event, data } = next;\n' +
    '      plausible(event, data);\n' +
    '      next = events.shift();\n' +
    '    }\n' +
    '  });\n' +
    '});\n' +
    'export let apiHost = "https://plausible.io";\n' +
    'export let compat = false;\n' +
    'export let domain = $page.url.hostname;\n' +
    'export let enabled = !dev;\n' +
    'export let fileDownloads = false;\n' +
    'export let hash = false;\n' +
    'export let local = enabled && dev;\n' +
    'export let outboundLinks = false;\n' +
    '$:\n' +
    '  api = `${apiHost}/api/event`;\n' +
    '$:\n' +
    '  src = [\n' +
    '    `${apiHost}/js/script`,\n' +
    '    compat ? "compat" : void 0,\n' +
    '    fileDownloads ? "file-downloads" : void 0,\n' +
    '    hash ? "hash" : void 0,\n' +
    '    local ? "local" : void 0,\n' +
    '    outboundLinks ? "outbound-links" : void 0,\n' +
    '    "js"\n' +
    '  ].filter(Boolean).join(".");\n' +
    '</script>\n' +
    '\n' +
    '<svelte:head>\n' +
    '\t{#if enabled}\n' +
    '\t\t<script data-api={api} data-domain={domain.toString()} defer {src}></script>\n' +
    '\t\t<script>\n' +
    '\t\t\twindow.plausible =\n' +
    '\t\t\t\twindow.plausible ||\n' +
    '\t\t\t\tfunction () {\n' +
    '\t\t\t\t\t(window.plausible.q = window.plausible.q || []).push(arguments);\n' +
    '\t\t\t\t};\n' +
    '\t\t</script>\n' +
    '\t{/if}\n' +
    '</svelte:head>\n'
}
```

**Comment by dgrebb** [comment]
@till apologies — I overlooked two things. In `dev` mode, `PlausibleAnalytics` is set to false by default. See [Line 59](https://github.com/accuser/svelte-plausible-analytics/blob/main/src/lib/PlausibleAnalytics.svelte#L59) of the `src/lib/PlausibleAnalytics.svelte` file.

Can you please try adding `enabled` to component props? Let's see what kinds of errors this yields.

I'm also curious, what is `ownDomain`'s value in the context of `<PlausibleAnalytics domain={[ownDomain, 'rollup.example.org']} />`?

**Comment by till** [comment]
`ownDomain` is a var I fill from Kit. Basically to filter out pre-prod environments.

**Comment by till** [comment]
I get the same error when I add enabled to it. I can't tell which src attribute it's referring to.

**Comment by dgrebb** [comment]
I believe it's referring to `src` from [Line 89](https://github.com/accuser/svelte-plausible-analytics/blob/main/src/lib/PlausibleAnalytics.svelte#L89), which is a `join`ed `string`.

@till If you `console.log(ownDomain)`, what is the value being passed into `<PlausibleAnalytics />`?

Edit: or [`@debug`](https://svelte.dev/docs/special-tags#debug), which I often forget.

**Comment by till** [comment]
@dgrebb I can't get it to print, it seems to "stop" before even getting to the layout. It seems like the page doesn't load, it stops with the pre-processing. Sorry, not very helpful.

**Comment by dgrebb** [comment]
What happens if you pass the value you expect to be in `ownDomain` directly, replacing the variable with a string?

eg. `<PlausibleAnalytics domain={['my.example.org', 'rollup.example.org']} />`?

**Comment by till** [comment]
@dgrebb I tried a few things to no avail:

- supplying a string (instead of `ownDomain` 👎🏼 
- upgraded kit and the adapter to their latest minor releases 👎🏼 

I then added a couple `console.log()` statements in the `.svelte` file (in dist), which got me further:

```js
  src = [
    `${apiHost}/js/script`,
    compat ? "compat" : void 0,
    fileDownloads ? "file-downloads" : void 0,
    hash ? "hash" : void 0,
    local ? "local" : void 0,
    outboundLinks ? "outbound-links" : void 0,
    "js"
  ].filter(Boolean).join(".");
	console.log("api ", api)
	console.log("enabled: ", enabled)
	console.log("src: ", src)
	console.debug("domain: " + domain.toString())
```

There, `src` **and** `api` are undefined. Hence the error. Everything else is set (the component properties I _injected_).

**Comment by till** [comment]
I looked at the current main branch here:

```js
	$: api = `${apiHost}/api/event`;
	$: src = [
		`${apiHost}/js/script`,
		compat ? 'compat' : undefined,
		fileDownloads ? 'file-downloads' : undefined,
		hash ? 'hash' : undefined,
		local ? 'local' : undefined,
		outboundLinks ? 'outbound-links' : undefined,
		'js'
	]
		.filter(Boolean)
		.join('.');
```

But in `dist`:

```js
$:
  api = `${apiHost}/api/event`;
$:
  src = [
    `${apiHost}/js/script`,
    compat ? "compat" : void 0,
    fileDownloads ? "file-downloads" : void 0,
    hash ? "hash" : void 0,
    local ? "local" : void 0,
    outboundLinks ? "outbound-links" : void 0,
    "js"
  ].filter(Boolean).join(".");
```

Anyhow, I am a big noob (for full transparency) so maybe my assumption is wrong, but it seems like the "reactive" syntax is broken by the release process, maybe?

Maybe it's also not necessary to use the `$:` there since you are assigning to a var and you don't have a method call, like, `src.update()`, but you are doing `src = 'foo'` already?

**Comment by till** [comment]
I fiddled with a smaller example in a repl: https://svelte.dev/repl/ea64318c76324babb8b44b3f7f3a37e5?version=4.2.8

It's _undefined_ as well, so it's not just broken syntax by the release process or whatever. But I still don't why.

**Comment by till** [comment]
I just re-read the docs to fight my noobness:
https://kit.svelte.dev/docs/state-management#component-and-page-state-is-preserved

So, that code "should" not be a problem. But I still can't figure out why `vite-plugin-svelte` barfs.

**Comment by dgrebb** [comment]
@till let's try:

1. Install this from npm directly, as [v1.0.0 was published](https://www.npmjs.com/package/@accuser/svelte-plausible-analytics/v/1.0.0) to npm
2. Load `PlausibleAnalytics` [on mount](https://svelte.dev/docs/svelte#onmount), instead of load, to be sure your variables are available:

```svelte
<script>
  import { PlausibleAnalytics } from "@accuser/svelte-plausible-analytics";
  import { onMount } from "svelte";

  let mounted = false;

  onMount(() => {
    mounted = true;
  });
</script>

<h1>Welcome to SvelteKit</h1>
<p>
  Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation
</p>

{#if mounted}
  <PlausibleAnalytics domain="example.com" enabled="true" />
{/if}
```

**Comment by dgrebb** [comment]
An [example of this](https://svelte.dev/repl/273a8ca010d944588e8acef562be0bd7?version=4.2.8) within the context of the REPL you included.

And [another example](https://svelte.dev/repl/6e4670bf4ef24fcb9e9765e50376ac80?version=4.2.8), but reversing where the `onMount` is called.

**Comment by till** [comment]
Installed the 1.0.0 and wrapped it in `{#if mounted}` but the error is still that the `src` is not a string.

**Comment by till** [comment]
Btw, why do you think my variables are the root of this? As far as I can see, all properties (e.g. via <PlausibleAnalytics domain=['foo', 'bar'] />` are available (inside) and set.

What somehow "fails" is the construction of the `src` variable inside the component.

**Comment by dgrebb** [comment]
Still scratching my head on this. I honed in on `ownDomain` because it sounds like everything works as expected until that is added in the `domain` prop. If `src` is not throwing a `src is not a string` until `ownDomain` is introduced, the suspicion is a malformed value in `ownDomain`, because `{src}` comes last in props:

```javascript
File: src/lib/PlausibleAnalytics.svelte
104: 		<script data-api={api} data-domain={domain.toString()} defer {src}></script>
```

But I don't know for a fact this is a culprit, only ideas to try. 

@till is this in a public branch/repo that you can share? Or is there a way to de-contextualize and post `svelte.config.jjs`, `vite.config.js`, and the component where this is implemented?

Another question came to mind — was this project originally SvelteKit 1.x? And if so, were the [SvelteKit 2 migration scripts](https://kit.svelte.dev/docs/migrating-to-sveltekit-2) run?

`npx svelte-migrate@latest sveltekit-2`

**Comment by till** [comment]
Sorry, this took a bit with holidays and last minute 2023 things.

So even when I remove `ownDomain` completely and fall back to the logic inside the component, it still bugs out at `src is not a string`.

And yes, I migrated from 1.x to 2.x but I already ran the migration scripts.

Here is my `svelte.config.js`:

```js
// import adapter from '@sveltejs/adapter-auto';
import adapter from '@sveltejs/adapter-static'
import preprocess from 'svelte-preprocess'

/** @type {import('@sveltejs/kit').Config} */
export default {
	extensions: ['.svelte'],
	kit: {
		alias: {
			$store: './src/store',
		},
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: 'index.html',
			precompress: false,
		}),
	},
	preprocess: [
		preprocess({
			postcss: true,
		}),
	],
}
```

My `vite.config.js`:

```js
// vite.config.js
import { defineConfig } from 'vite'
import { sveltekit } from '@sveltejs/kit/vite'
import path from 'path'

export default defineConfig({
	build: {
		minify: true,
	},
	resolve: {
		alias: {
			$routes: path.resolve('./src/routes'),
			$store: path.resolve('./src/store'),
		},
	},
	plugins: [sveltekit()],
})
```

My guess is, this is some kind of build problem. 

My `package.json`:

```json
{
  "name": "ui",
  "private": true,
  "version": "0.0.1",
  "engines": {
    "node": ">=v18.0.0"
  },
  "scripts": {
    "dev": "vite --host --port 3000",
    "build": "vite build",
    "package": "svelte-kit package",
    "preview": "vite preview",
    "lint": "prettier --ignore-path .prettierignore --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
    "format": "prettier --ignore-path .prettierignore --write --plugin-search-dir=. .",
    "check": "tsc -p tsconfig.json --allowJs --checkJs --noEmit",
    "test": "playwright test"
  },
  "devDependencies": {
    "@accuser/svelte-plausible-analytics": "^1.0.0",
    "@dinero.js/currencies": "2.0.0-alpha.13",
    "@ory/client": "^1.1.21",
    "@playwright/test": "^1.31.2",
    "@sveltejs/adapter-static": "^3.0.1",
    "@sveltejs/kit": "^2.0.6",
    "@sveltejs/vite-plugin-svelte": "^3.0.0",
    "@tailwindcss/typography": "^0.5.2",
    "autoprefixer": "^10.4.7",
    "daisyui": "^2.51.3",
    "dinero.js": "2.0.0-alpha.13",
    "eslint": "^8.35.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-svelte": "^2.35.1",
    "layercake": "^7.4.0",
    "parse-duration": "^1.0.3",
    "postcss": "^8.4.14",
    "prettier": "^2.4.1",
    "prettier-plugin-svelte": "^2.10.1",
    "prometheus-query": "^3.3.0",
    "svelte": "^4.0.0",
    "svelte-check": "^3.4.3",
    "svelte-forms-lib": "^2.0.1",
    "svelte-preprocess": "^5.0.3",
    "tailwindcss": "^3.2.4",
    "vite": "^5.0.0",
    "vitest": "^1.0.0",
    "vitest-fetch-mock": "^0.2.2",
    "ws": "^8.12.1",
    "yup": "^0.32.11",
    "yup-password": "^0.2.2"
  },
  "type": "module"
}
```

**Comment by till** [comment]
I can't really share a lot of code otherwise, but my "implementation" is only in my root layout currently:

```js
# src/routes/+layout.svelte
<script>
	// @ts-check
	import Loading from '$lib/components/Loading.svelte'
	import TopNav from '$lib/components/TopNav.svelte'
	import '../app.css'
	import { PlausibleAnalytics } from '@accuser/svelte-plausible-analytics'
	import Toast from '$lib/components/Notifications.svelte'
	import { onMount } from 'svelte'

	let mounted = false
	onMount(() => {
		mounted = true
	})
</script>
<Loading />
<TopNav />
<main class="grow p-5 w-full flex flex-col items-center">
	<Toast />
	<slot />
</main>
<footer class="footer p-10 bg-base-200 text-base-content">
 <!-- ... -->
</footer>
{#if mounted}
	<PlausibleAnalytics enabled={true} />
{/if}
```

**Comment by dgrebb** [comment]
@till thank you — this was helpful.

Remove this:

```javascript
File: svelte.config.js
20: 	preprocess: [
21: 		preprocess({
22: 			postcss: true,
23: 		}),
24: 	],
```

and it compiles without issue.

I'll do a little digging into what is going on, but this doesn't have anything to do with `svelte-plausible-analytics`. The errors indicate as much, if you dig passed the first error. `svelte-preprocess` seems to be hung up on `at getTagInfo /Users/dgrebb/projects/tmp/sveltekit2-debug/node_modules/svelte-preprocess/dist/modules/tagInfo.js:32:19)`

I would have noticed this sooner, but have never done any pre-pre-preprocessing before. Check out [this issue on the `svelte-preprocess` repo](https://github.com/sveltejs/svelte-preprocess/issues/604), which appears to be the issue you're encountering.

By the way, you're using TypeScript with this project :)

**Comment by till** [comment]
Ah! I think I got that from the boilerplate when I created my app a while back.

I'll dig into it as well. :) Thanks for helping me out!

Btw, I am using TypeScript for jsdoc only. Didn't think it matters, sorry about that!

**Comment by dgrebb** [comment]
The TypeScript bit may impact some of this — there's a `// @ts-check` in `+layout.svelte`. I know enough to understand syntax and type projects, but am not a TypeScript expert by any means. 

If the only thing you need to preprocess is postcss, check out some of the configuration below. You _may_ be able to pull `svelte-preproces` out entirely:

## PostCSS running in `vite.config.js`:

- https://github.com/dgrebb/dgrebb.com/blob/develop/front/vite.config.js#L7
- https://github.com/dgrebb/dgrebb.com/blob/develop/front/vite.config.js#L21

## Using `vitePreprocess`

- https://github.com/dgrebb/dgrebb.com/blob/develop/front/svelte.config.js#L7

## And a `postcss.config.js`

- https://github.com/dgrebb/dgrebb.com/blob/develop/front/postcss.config.js

Good luck @till!

**Comment by dgrebb** [comment]
@accuser this was a good learning dialog. 

We could make a change to protect against [`svelte-preprocess` issues with `{src}` vs. `src={src}`](https://github.com/sveltejs/svelte-preprocess/issues/604), though I think eventually a code formatter will undo it ¯\\\_(ツ)\_/¯

## File: `src/lib/PlausibleAnalytics.svelte`

```diff
-               <script data-api={api} data-domain={domain.toString()} defer {src}></script>
+               <script data-api={api} data-domain={domain.toString()} defer src={src}></script>
```

**Comment by dgrebb** [comment]
Another option, to prevent Prettier/ESLint over-zealousness:

```diff
diff --git a/src/lib/PlausibleAnalytics.svelte b/src/lib/PlausibleAnalytics.svelte
index 13870dd..e488545 100644
--- a/src/lib/PlausibleAnalytics.svelte
+++ b/src/lib/PlausibleAnalytics.svelte
@@ -86,7 +86,7 @@
        export let outboundLinks = false;

        $: api = `${apiHost}/api/event`;
-       $: src = [
+       $: plausibleSrc = [
                `${apiHost}/js/script`,
                compat ? 'compat' : undefined,
                fileDownloads ? 'file-downloads' : undefined,
@@ -101,7 +101,7 @@

 <svelte:head>
        {#if enabled}
-               <script data-api={api} data-domain={domain.toString()} defer {src}></script>
+               <script data-api={api} data-domain={domain.toString()} defer src={plausibleSrc}></script>
                <script>
                        window.plausible =
                                window.plausible ||
```

**Comment by till** [comment]
> The TypeScript bit may impact some of this — there's a `// @ts-check` in `+layout.svelte`. I know enough to understand syntax and type projects, but am not a TypeScript expert by any means. 

Allows/Enables editor/ide to do basic type checking via provided types by libs or jsdoc. That's all.

Besides, I've also never written a line of ts in my life. 😁
